---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excelapi
spec:
  selector:
    matchLabels:
      app: excelapi
  template:
    metadata:
      labels:
        app: excelapi
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker-node01
                # - antarctica-west1
      containers:
      - name: excelapi
        image: sudoharish/excelapi:latest
        resources:
          limits:
            memory: "128Mi"
            # cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: excelapi
spec:
  selector:
    app: excelapi
  # type: LoadBalancer
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
---